# Generated by Django 4.2 on 2023-05-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
