# Generated by Django 4.2 on 2023-05-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_items',
            field=models.IntegerField(default=1),
        ),
    ]
